function [Fitness,pop,BreakPipe_result,RepairCrew_result,...
    F,system_L,system_serviceability,node_serviceability,node2_serviceability,...
    node_calculate_dem,node_calculate_pre,timeStep_end]=random_priority2(MC_simulate_result_dir_random,MC_i,...文件夹，模拟次数
    BreakPipe_order,RepairCrew,...破坏管道，修复队伍，
    damage_pipe_info,net_data,...破坏信息，管网信息，
    EPA_format,...node_original_data,system_original_L,...EPA格式，节点原本数据，系统原本管道长度
    circulation_num,doa,Hmin,Hdes,...PDD迭代次数，精度，最小水压，需要水压
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...检查时间，修复时间，移动时间
    output_net_filename,pipe_relative)%
% 采用随机次序进行震后修复过程

[pop]=pipeDamage2priorityList(BreakPipe_order);%产生随机次序
% node_original_dem=cell2mat(node_original_data(:,2));%节点原本的需水量
% original_junction_num=numel( node_original_dem);%节点个数
 [Fitness,BreakPipe_result,RepairCrew_result,F,system_L,system_serviceability,node_serviceability,node2_serviceability,node_calculate_dem,node_calculate_pre,timeStep_end,timeStep,activity_cell]...
     =fit4...
     (pop,...
     RepairCrew,...
     BreakPipe_order,...
            Dp_Inspect_mat,...
            Dp_Repair_mat,Dp_Travel_mat,...original_junction_num,
            damage_pipe_info,net_data,...
            MC_i,0,0,MC_simulate_result_dir_random,MC_simulate_result_dir_random,MC_simulate_result_dir_random,...
            EPA_format,...node_original_data,
            circulation_num,doa,Hmin,Hdes,...node_original_dem,system_original_L,...
            output_net_filename,...
            pipe_relative,'on');%评价种群个体适应度
end