% 新建一个变量，记录模拟过的个体，并比较
% 当采用epanetx64pdd.dll时，改写的遗传府过程。在ga_priority6.m的基础上修改。
function [pop_isolation_record,Fit_record]...
    =ga_priority9_epanetx64pdd(popsize,generation_Nmax,pc,pm,...种群大小，进化代数，交叉概率，变异概率
    out_dir,....输出目录
    RepairCrew,...修复队伍，
    damage_pipe_info,net_data,pipe_relative,...破坏信息，管网信息，破坏管道相关新建管道
    EPA_format,...node_original_data,system_original_L,...EPA格式，节点原本数据，系统原本管道长度
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...检查时间，修复时间，移动时间
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel,...
    output_net_filename_inp)%,...
% process_1 the optimization of isolation priority
BreakPipe_order = damage_pipe_info{1}(damage_pipe_info{3}==2);%需要隔离的管道
[pop_isolation_init]=initpop4(popsize,BreakPipe_order);
pop_isolation_record = pop_isolation_init;%记录个体
Fit_isolation_max = zeros(generation_Nmax,1);
Fit_isolation_mean = zeros(generation_Nmax,1);
pop_isolation_uniq = pop_isolation_init;
for generation_i = 1:generation_Nmax
    generation_dir_i=[out_dir,'process_1\','遗传第',num2str(generation_i),'代\'];
    mkdir(generation_dir_i);
    
    if ~isempty(pop_isolation_uniq)
        [Fit_isolation_uniq,fitvalue_isolation]=calfitvalue4_isolation(pop_isolation_uniq,damage_pipe_info{1},RepairCrew,...
            Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...
            crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel,...
            damage_pipe_info,net_data,...
            EPA_format,...
            generation_dir_i,...
            output_net_filename_inp,pipe_relative);%,...
    else
        generation_i = generation_Nmax+1;
        disp('haha')
        break
    end
    if generation_i==1
        Fit_init = Fit_isolation_uniq;
        Fit_record = Fit_init;
        pop_isolation_old = pop_isolation_init;
    else
        Fit_init(locb1) = Fit_isolation_uniq;
        Fit_init(locb2) = Fit_record(locb3);
        Fit_record = [Fit_record;Fit_init];
        pop_isolation_old = newPop_isolation;
        % pop_uniq(lia1,:)
    end
    Fit_isolation_max(generation_i,1) = max(Fit_init);
    Fit_isolation_mean(generation_i,1) = mean(Fit_init);
    [ newPop_isolation ] = ga_process( pop_isolation_old,Fit_init,pm,pc );
    [ pop_uniq,pop_uniq_not,new_individual_record_mat ] = ga_unique_individual3( newPop_isolation,pop_isolation_record );
    [lia1,locb1] = ismember(pop_uniq,newPop_isolation,'rows');
    [lia2,locb2] = ismember(pop_uniq_not,newPop_isolation,'rows');
    [lia3,locb3] = ismember(pop_uniq_not,pop_isolation_record,'rows');
    pop_isolation_uniq = pop_uniq;
    pop_isolation_record=new_individual_record_mat;
end
[a1,a2] = max(Fit_record); 
best_indivi_isolation = pop_isolation_record(a2,:);
x_isolation= 1:generation_Nmax;
y1_isolation=Fit_isolation_max';
y2_isolation=Fit_isolation_mean';
y3_isolation = reshape(Fit_record,popsize,generation_Nmax);
figure(1)
plot(x_isolation,y1_isolation);
hold on
plot(x_isolation,y2_isolation);
plot(repmat(x_isolation,popsize,1),y3_isolation,'*')
hold off
% process_2 the optimization of recovery reiority
DamagePipe_order = damage_pipe_info{1};%需要修复的管道
[pop_recovery_init]=initpop4(popsize,DamagePipe_order);
pop_recovery_record = pop_recovery_init;%记录个体
Fit_recovery_max = zeros(generation_Nmax,1);
Fit_recovery_mean = zeros(generation_Nmax,1);
pop_recovery_uniq = pop_recovery_init;
for generation_i = 1:generation_Nmax
    generation_dir_i=[out_dir,'process_2\','遗传第',num2str(generation_i),'代\'];
    mkdir(generation_dir_i);
    
    if ~isempty(pop_recovery_uniq)
        [Fit_recovery_uniq,fitvalue]=calfitvalue4_recovery(best_indivi_isolation,pop_recovery_uniq,DamagePipe_order,RepairCrew,...
     Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...
     crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel,...
    damage_pipe_info,net_data,...
    EPA_format,...
    generation_dir_i,...
output_net_filename_inp,pipe_relative);%,....

    end
    if generation_i==1
        Fit_init = Fit_recovery_uniq;
        Fit_recovery_record = Fit_init;
        pop_recovery_old = pop_recovery_init;
    else
        Fit_init(locb1_re) = Fit_recovery_uniq;
        Fit_init(locb2_re) = Fit_recovery_record(locb3_re);
        Fit_recovery_record = [Fit_recovery_record;Fit_init];
        pop_recovery_old = newPop_recovery;
        % pop_uniq(lia1,:)
    end
    Fit_recovery_max(generation_i,1) = max(Fit_init);
    Fit_recovery_mean(generation_i,1) = mean(Fit_init);
    [ newPop_recovery ] = ga_process( pop_recovery_old,Fit_init,pm,pc );
    [ pop_uniq_recovery,pop_uniq_not_recovery,new_individual_record_mat_recovery ] = ga_unique_individual3( newPop_recovery,pop_recovery_record );
    [lia1,locb1_re] = ismember(pop_uniq_recovery,newPop_recovery,'rows');
    [lia2,locb2_re] = ismember(pop_uniq_not_recovery,newPop_recovery,'rows');
    [lia3,locb3_re] = ismember(pop_uniq_not_recovery,pop_recovery_record,'rows');
    pop_recovery_uniq = pop_uniq_recovery;
    pop_recovery_record=new_individual_record_mat_recovery;
end
[b1,b2] = max(Fit_record); 
best_indivi_recovery = pop_recovery_record(b2,:);
x_recovery= 1:generation_Nmax;
y1_recovery=Fit_recovery_max';
y2_recovery=Fit_recovery_mean';
y3_recovery = reshape(Fit_recovery_record,popsize,generation_Nmax);
figure(2)
plot(x_recovery,y1_recovery);
hold on
plot(x_recovery,y2_recovery);
plot(repmat(x_recovery,popsize,1),y3_recovery,'o')
hold off
% process 3
individual_dir_i ='.\results';
try
[Fitness_end,...
        BreakPipe_result,...
        RepairCrew_result,...
        system_serviceability_cell,...
        activity_cell]...
        =fit7_recovery...
        (best_indivi_isolation,best_indivi_recovery,...
        DamagePipe_order,RepairCrew,...
        Dp_Inspect_mat,...
        Dp_Repair_mat,Dp_Travel_mat,...
        net_data,...
        individual_dir_i,...
        output_net_filename_inp,...
        pipe_relative,...
        crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel)%评价种群个体适应度
catch
    keyboard
end
end
function [Fit,fitvalue]=calfitvalue4_isolation(pop,BreakPipe_order,RepairCrew,...
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel,...
    ~,net_data,...
    ~,...
    generation_dir_i,...
    output_net_filename_inp,pipe_relative)%,...
popsize = numel(pop(:,1));
Fitness= zeros(popsize,1);
fitvalue=cell(popsize,15);
for individual_i=1:popsize
    individual_dir_i=[generation_dir_i,'\',num2str(individual_i),'\'];
    mkdir(individual_dir_i)
    BreakPipePriority=pop(individual_i,:);
    %fit5
    [Fitness(individual_i),...
        BreakPipe_result,...
        RepairCrew_result,...
        system_serviceability_cell,...
        activity_cell]...
        =fit7_isolation...
        (BreakPipePriority,...
        BreakPipe_order,RepairCrew,...
        Dp_Inspect_mat,...
        Dp_Repair_mat,Dp_Travel_mat,...
        net_data,...
        individual_dir_i,...
        output_net_filename_inp,...
        pipe_relative,...
        crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel)%评价种群个体适应度
end
Fit = Fitness;
end
function [Fitness,...
    BreakPipe_result,...
    RepairCrew_result,...
    system_serviceability_cell,...
    activity_cell]...
    =fit7_isolation...
    (BreakPipePriority,...
    BreakPipe_order,RepairCrew,...
    Dp_Inspect_mat,...
    Dp_Repair_mat,Dp_Travel_mat,...
    net_data,...
    output_result_dir,...
    output_net_filename_inp,...
    pipe_relative,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel)%评价种群个体适应度
funcName = 'fit7_isolation';
BreakPipePriority_cell = num2cell(BreakPipePriority');
DamagePipePriority_cell = num2cell(BreakPipe_order);
[BreakPipe_result,RepairCrew_result]=priorityList2schedule10_2_step_one(BreakPipePriority_cell,RepairCrew,DamagePipePriority_cell,...
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,output_result_dir,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel);%根据修复次序生成时间表，隔离与修复分开的策略 from 'random\'
[PipeStatus2,PipeStatusChange]=schedule2pipestatus5_isolation(BreakPipe_result,BreakPipe_order);%根据时间表生成管道状态矩阵
if isempty(PipeStatus2)
    PipeStatus = ones(numel(BreakPipe_order),168*2)*2;%没有修复的延时模拟过程。
else
    PipeStatus = PipeStatus2;
end
duration_one = numel(PipeStatus(1,:));
[ errcode,Pre,Demand,cal_Demand, system_serviceability_cell,activity_cell] = EPS_net4_EPANETx64PDD( output_net_filename_inp,output_result_dir,PipeStatus,PipeStatusChange,pipe_relative,net_data,...
    duration_one);
Fitness = sum(cell2mat(system_serviceability_cell))/duration_one;
end
function [Fit,fitvalue]=calfitvalue4_recovery(indivi_isolation,pop,BreakPipe_order,RepairCrew,...
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel,...
    ~,net_data,...
    ~,...
    generation_dir_i,...
    output_net_filename_inp,pipe_relative)%,...
popsize = numel(pop(:,1));
Fitness= zeros(popsize,1);
fitvalue=cell(popsize,15);
for individual_i=1:popsize
    individual_dir_i=[generation_dir_i,'\',num2str(individual_i),'\'];
    mkdir(individual_dir_i)
    BreakPipePriority=pop(individual_i,:);
    %fit5
    [Fitness(individual_i),...
        BreakPipe_result,...
        RepairCrew_result,...
        system_serviceability_cell,...
        activity_cell]...
        =fit7_recovery...
        (indivi_isolation,BreakPipePriority,...
        BreakPipe_order,RepairCrew,...
        Dp_Inspect_mat,...
        Dp_Repair_mat,Dp_Travel_mat,...
        net_data,...
        individual_dir_i,...
        output_net_filename_inp,...
        pipe_relative,...
        crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel)%评价种群个体适应度
end
Fit = Fitness;
fitvalue{1,1} = system_serviceability_cell;
end
function [Fitness,...
    BreakPipe_result,...
    RepairCrew_result,...
    system_serviceability_cell,...
    activity_cell]...
    =fit7_recovery...
    (indivi_isolation,BreakPipeRecoveryPriority,...
    BreakPipe_order,RepairCrew,...
    Dp_Inspect_mat,...
    Dp_Repair_mat,Dp_Travel_mat,...
    net_data,...
    output_result_dir,...
    output_net_filename_inp,...
    pipe_relative,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel)%评价种群个体适应度
funcName = 'fit7_recovery';
BreakPipePriority_cell = num2cell(indivi_isolation');
DamagePipePriority_cell = num2cell(BreakPipeRecoveryPriority');
[BreakPipe_result,RepairCrew_result]=priorityList2schedule9(BreakPipePriority_cell,DamagePipePriority_cell,RepairCrew,num2cell(BreakPipe_order),...
    Dp_Inspect_mat,Dp_Repair_mat,Dp_Travel_mat,output_result_dir,...
    crewStartTime,crewEfficiencyRecovery,crewEfficiencyIsolation,crewEfficiencyTravel);%根据修复次序生成时间表，隔离与修复分开的策略 from 'random\'
[PipeStatus2,PipeStatusChange]=schedule2pipestatus4(BreakPipe_result);%根据时间表生成管道状态矩阵
if isempty(PipeStatus2)
    PipeStatus = ones(numel(BreakPipe_order),168*2)*2;%没有修复的延时模拟过程。
else
    PipeStatus = PipeStatus2;
end
duration_one = numel(PipeStatus(1,:));
[ errcode,Pre,Demand,cal_Demand, system_serviceability_cell,activity_cell] = EPS_net4_EPANETx64PDD( output_net_filename_inp,output_result_dir,PipeStatus,PipeStatusChange,pipe_relative,net_data,...
    duration_one);
Fitness = sum(cell2mat(system_serviceability_cell))/duration_one;
end